### ISSUE TITLE
Sentencepiece to OpenNMTpy vocab creates same id for unk token and user defined symbols

### ISSUE THREAD

**Issue by anuragshas** [ymoslem/MT-Preparation#6]
Hi,
If I create tokenizer using sentencepiece and convert to OpenNMTpy using the file **subwording/spm_to_vocab.py** it create same ids for the unknown token and user defined symbols, so if I use replace_unk parameter in opennmtpy while translating, it will replace with one of the user defined symbols and not unk token.
I hope my deduction is right and I can work on the fix here or in the tools file of OpenNMTpy.

**Comment by ymoslem** [comment]
Hello! The option `replace_unk` with a Transformer model tries to replace the unk token with the matching token from the source. My understanding is that for this option to work well, the model needs to be trained with the “guided alignment” feature. Otherwise, it might just delete the unk token without doing anything else.
